# Generated by Django 3.2.7 on 2021-10-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartmentnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartmentnumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.PositiveIntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.PositiveIntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sale', 'Sale'), ('buy', 'Buy'), ('rent', 'Rent')], max_length=5)),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House')], max_length=9)),
                ('rooms', models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five or more')], max_length=5)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField(max_length=100)),
                ('apartmentnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.apartmentnumber')),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.entrance')),
                ('floors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.floors')),
            ],
        ),
    ]
